CREATE TABLE [dbo].[Product]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UserId] INT NOT NULL FOREIGN KEY REFERENCES [User](Id),
    [Name] NVARCHAR(50) NOT NULL, 
    [Brand] NVARCHAR(50) NOT NULL, 
    [Price] MONEY NOT NULL, 
    [Description] NVARCHAR(2000) NOT NULL,
    [Category] NVARCHAR(50) NOT NULL,
    [ImageName] NVARCHAR(50) NOT NULL
)
